### ISSUE TITLE
0.5 release

### ISSUE THREAD

**Issue by jkarni** [haskell-servant/servant#251]
This issue is to keep track of what we think we need to do before the release. My take of issues that are either important, or basically done. Please remind of things I might have forgotten:

- [x] Use http-api-data: #250
- [x] More generous http status codes for servant-client: #249 
- [ ] Make `Raw` work with `Enter` (and pave way for servant snap) #248 
- [x] Use text in servant-js and -foreign #243 .
- [x] Fix servant-client tests #245. 
- [x] Routing changes. I think for this we should go with kosmikus' version, and remove my posterious commits: #218 
- [x] Auth: #199 . This is, I think, what still needs most work.

Additionally, we should talk about whether we want to (temporarily) remove `MatrixParams` (for the reasons listed in #113). Trying to fix it would put off the release.

And then tutorial updates, and a read through the haddocks. *EDIT*: And a look that nothing is missing from the changelogs.

Except for the last three, I think all are ready for review. Please consider helping with that. I'll volunteer for reviewing #250, and getting #218 back to the state we want. If we decide to remove `MatrixParams`, I can do that too. @arianvp can you rebase branch `245` into #245 again? And what is left for #199? How long do you think it'll take to get it ready for review?

Should we say Oct. 24 as the aim for merging all of these? 

Mentioning people who have been involved with these changes in some way: @codedmart @alpmestan @kosmikus @soenkehahn @aaronlevin @arianvp

**Comment by jkarni** [comment]
@fizruk @dredozubov

**Comment by dredozubov** [comment]
Oh, great! It went faster than i expected. I'll try to free some time and go through relevant PRs.
Also FWIW i tend to think that it's ok to remove `MatrixParams`.

**Comment by arianvp** [comment]
#199 is a bit of an old pull request. If we're gonna include digest auth, we can combine it in #185.

I think we already have a powerful feature list if we release #185 as is  (JWT + Basic Auth). It allows for a cool use case of having a BasicAuth token-granting endpoint and protecting outer endpoints with the JWT token.

For what still needs to happen for #185 
* Add tests for the JWT code
* Make sure servant-docs works. Perhaps add some ToSample instances if needed.
* More documentation. not everything has haddock documentation yet.
* An example / tutorial

This I definitely can finish before the 24th.

For Digest auth we'll need to find out away to elegantly allow the the client to request a nonce for a specific resource. Or to automatically do the extra request needed for that, which would require some state bookkeeping in `servant-client`. I still don't really have a well established opinion what's the best approach here. I hope to find some time soon to come up with something elegant.

**Comment by freezeboy** [comment]
@arianvp About authentication, isa "bearer" header also included in the current implementation ?

**Comment by arianvp** [comment]
@freezeboy You're talking about this RFC right? https://tools.ietf.org/html/rfc6750

The `JWT` implementation is a "bearer" scheme.  (Except that it doesn't return a `WWW-Authenticate` header correctly yet, but i'll create an issue for that to fix it)   Though it might be worth to generalize it to any kind of token. 

This might be worth adding actually and shouldn't be too much work I think. Especially to have interop with other OAUTHv2 servers in the future that don't use JWT for tokens but use their own form of HMAC

**Comment by arianvp** [comment]
@freezeboy to continue on that point.  We could  create some kind of typeclass called `VerifyToken`  with a single method `verify`  so that we can abstract away the `JWT`-specific stuff. That way we could be fully RFC compliant.

**Comment by aaronlevin** [comment]
@arianvp there is an example using a bespoke / custom cookie-based authentication here: https://github.com/aaronlevin/servant/blob/auth/servant-examples/auth-combinator/auth-combinator.hs

**Comment by aaronlevin** [comment]
I can write a tutorial for authentication, but I need to know *where* it should go? Are there existing examples? Preferably this would live with the current servant documentation?

**Comment by alpmestan** [comment]
It'd go in [the tutorial](http://haskell-servant.github.io/tutorial/).

**Comment by jml** [comment]
Just a note to say that I'd love a 0.5 release even if it added 0 new features. The relief of being able to use `ExceptT` directly would be joy enough.

**Comment by soenkehahn** [comment]
@jml: Yes, me too. I also think the `Raw` issue shouldn't block a release. If I'm not missing anything important, these are the last things that *are* blocking the release:

- review and merge #355 (some discussion also in #360) and
- update `Javascript.lhs` in that branch to reflect how javascript code generation works on master.

**Comment by codedmart** [comment]
@soenkehahn I was under the impression Raw wasn't going to be in 0.5, but I can finish it up the beginning of the week if needed.

**Comment by soenkehahn** [comment]
@codedmart: Sorry, I should have expressed myself a little clearer. We have a checklist at the very top of this issue that still lists the `Raw` issue. I just wanted to clarify that this should not block a release IMO. So that list at the top is outdated.
